rustsec/rustsec

- .travis.yml
- Cargo.lock
- Cargo.toml
- src/main.rs
Uses the `rustsec` crate to fetch the security advisory database, then compares
it against crates in Cargo.lock.
Provides colorful reports of which crates are vulnerable, then exits with a
non-zero status if there are any vulnerable crates.
Pretty hacky code... could use a lot of work. But it's a start.
---
> Initial implementation

- Cargo.lock
- src/lockfile.rs
Treat the absence of a `[[package]]` section as no dependencies
> Avoid panicking if there are no dependencies (fixes #4)

- Cargo.lock
- Cargo.toml
- src/display.rs
- src/main.rs
This commit borrows some color/terminal handling code from cargo (with the hopes
of eventually getting this code merged into cargo proper).
Color support is now autodetected but also configurable as a "--color" command
line parameter (ala cargo itself)
> Configurable colors (fixes #5)

- Cargo.lock
- Cargo.toml
- appveyor.yml
- src/main.rs
- src/shell.rs
Error was lack of `isatty()` method and failing to resolve enums in scope (full error message at bottom):
* Remove custom `isatty()` functions in favor of using `isatty::stdout_isatty()`
* Qualify NoColor/Color with Terminal:: in windows `get_term()`
**Security Vulnerability:**
* Regenerated Cargo.lock so project is using newer hyper-tls version to resolve vulnerability (found with this tool).
**Not essential to fix:**
* Removed semver and toml as they aren't used.
* Swap `cfg(unix)` to `cfg(not(windows))`.
* Cargo Fmt ran over the project.
**Full build error:**
```   Compiling cargo-audit v0.2.0
Running `rustc --crate-name cargo_audit C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-audit-0.2.0\src\main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C …
```
> Use crate isatty to resolve Windows build errors

- Cargo.toml
- src/main.rs
- src/shell.rs
This is a cross-cutting update of several parts of this tool which replaces the following:
- rustsec 0.7 crate (w\ git-based advisory-db fetcher)
- gumdrop-based option parser
- macro-based shell API
> Near rewrite of cargo-audit (upgrades to rustsec 0.7.0)

- src/main.rs
- src/shell.rs
This makes usage of commas in `VersionReq`s less ambiguous
> Use ' OR ' delimiter to display patched versions (fixes #18)

- src/main.rs
This shouldn't exit with an error (e.g. breaks in CI)
> Have 'cargo audit version' exit with status 0

- .travis.yml
- README.md
This is the minimum Rust version supported by `cargo audit`
> .travis.yml: Test against Rust 1.25+

- .travis.yml
- src/main.rs
Supercedes #48 and #49 and should close both when merged.
> Fixes macro_use and bumps to 1.26.2 on Travis

- src/main.rs
Beta channel builds were failing on this from the `deny(warnings)`. This enables building against all of 1.25.0, stable, and beta as of the present.
> Allows macro_use that is unused on beta channel

- .travis.yml
This is necessary to pick up some functions introduced in 1.26.0 that transitive dependency libssh2-sys-0.2.11 requires.
Unblocks a #48, which unblocks #41.
> Bumps minimum Rust version on Travis to 1.26.2

- Cargo.toml
- src/main.rs
- src/shell.rs
Fixes #40 
⚠️ This cannot be merged until
> Adds --json flag to output JSON to STDOUT

- src/main.rs
gumdrop 0.5 seems to have changed the semantics of how it handles default `String` command-line arguments.
This changes all previous optional `String` command-line arguments with a default to an `Option<String>`.
> Fix option parsing (closes #63)

- README.md
Improves performance after `cargo-audit` has been installed the first time
> README.md: Document use of "cache: cargo" on Travis CI

- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
- src/shell.rs
- tests/integration.rs
- Updates `gumdrop` to v0.6
- Updates `rustsec` to v0.12 - requires Rust 1.32+
> Update gumdrop and rustsec crate dependencies; Rust 1.32+

- Cargo.lock
- Cargo.toml
- src/commands/audit.rs
- src/error.rs
Switches to the soon-to-be `rustsec` v0.13 crate, leveraging its query and report generation features.
> Upgrade to new (unreleased) `rustsec` crate

- Cargo.lock
- Cargo.toml
- src/commands/audit.rs
- src/lib.rs
- src/tree.rs
Shows a complete tree of dependencies associated with each vulnerable package in the lockfile.
This is useful for determining how vulnerable packages are being pulled into the project.
> Display dependency trees with each advisory

- Cargo.lock
- src/commands/audit.rs
Presently hardcoded to only unmaintained crates, but potentially configurable in the future.
> Display warnings for select informational advisories

- src/commands/audit.rs
Checks the included `rustsec` crate version against signaling coming from the Advisory DB itself to determine if an obsolete version of `cargo-audit` is in use.
> Warn for outdated `rustsec` crate versions

- src/commands/audit.rs
This was broken after the migration to Abscissa, which normally handles it in its toplevel entrypoint command.
This adds it back as an explicit option.
> Add (back) --help option

- Cargo.lock
- Cargo.toml
- audit.toml.example
- src/application.rs
- src/auditor.rs
- src/commands.rs
- src/commands/audit.rs
- src/config.rs
- src/lib.rs
- tests/config.rs
Extracts the core functionality from `AuditCommand` into a new `Auditor` type which deals with performing the audit.
Additionally moves all auditing options into `AuditConfig` and uses Abscissa's `config::Override` to populate them from command-line arguments.
> Extract `Auditor` and populate `AuditConfig`

- Cargo.lock
- Cargo.toml
Ensures that the next `cargo-audit` release will always be built with this version at a minimum, which should help when communicating about whether or not the bugs in the previous release were fixed.
> Update to `rustsec` crate v0.14.1

- src/auditor.rs
- src/commands/audit.rs
In cases where it makes sense, automatically generates the lockfile if it doesn't exist as part of the audit process.
> Run `cargo generate-lockfile` automatically

- src/presenter.rs
Previously, if no solution is available, it will simplyprint `Solution: upgrade to <<nothing>>`.
This commit changes that and will mention the fact that no advisable upgrade is available...
> Print the fact that no solution is available

- Cargo.lock
- Cargo.toml
This version contains an important bugfix, so it will be nice to know that the next release of cargo-audit always contains it.
https://github.com/RustSec/rustsec-crate/pull/122
> Upgrade to rustsec v0.15.2

- Cargo.lock
- Cargo.toml
- src/commands/audit.rs
Seems there were some SemVer breakages here, but fortunately we were always locked to a specific version.
Discussion here:
https://github.com/killercup/cargo-edit/issues/366
> Upgrade `cargo-edit` to v0.4.2

- Cargo.lock
- Cargo.toml
- audit.toml.example
- src/commands/audit.rs
- src/config.rs
This merge should wait for [RustSec/rustsec-crate#128](https://github.com/RustSec/rustsec-crate/pull/128)
> Fixes #169 - Dependency on workspace crate are handled wrong

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- audit.toml.example
- src/commands/audit.rs
- src/commands/audit/fix.rs
- src/config.rs
- src/lib.rs
Splits out `audit fix` from `audit` into its own subcommand with its own arguments.
Uses `rustsec::fixer::Fixer` as the implementation.
> Refactor `cargo audit fix` into a subcommand

- src/commands/audit.rs
- src/commands/audit/fix.rs
Support for displaying usage for the `fix` subcommand.
> Implement `cargo audit fix -h`

- Cargo.lock
- Cargo.toml
This activates the corresponding feature in the `rustsec` crate, which instructs `git2` to build with a vendored copy of OpenSSL instead of the system one.
> Add `vendored-openssl` feature (fixes #163)

- audit.toml.example
- src/application.rs
- src/commands.rs
- src/commands/audit.rs
- src/config.rs
Looks like this was lost in the shuffle of the migration to Abscissa.
This adds support for introspecting the command line arguments from Abscissa's `term_colors` callback, extracting the `-c` option and using it to configure color preferences if present.
This removes the associated configuration options, as this setting is processed too early in the Abscissa application lifecycle for this option to be able to be read from the config.
It seems like Abscissa could use a few improvements here both to reduce the amount of boilerplate required to wire all of this up and also to allow color preferences to be loaded from configuration, however for now this is sufficient to make the option work.
> Wire up `-c`/`--color` command line argument (fixes #177)

- Cargo.lock
- Cargo.toml
- audit.toml.example
- src/auditor.rs
- src/config.rs
Upgrades to `rustsec` crate v0.18.
This commit moves the functionality of the `find_yanked_crates()` function which was previously located in the `rustsec` crate into `cargo-audit` itself, which allows printing contextual messages about its interactions with the crates.io index:
https://github.com/RustSec/rustsec-crate/pull/147
It also adds config options to disable auditing for yanked crates, or to disable fetching the crates.io index before checking for yanked crates.
> Improve yanked crate auditing messages and config

- Cargo.lock
Version 0.3.42 used previously has been yanked, causing self-audit warnings. The reason it was yanked was due to some versioning issue with the `cfg-if` dependency, so it's not a security issue but it does cause CI to fail.
See <https://github.com/rust-lang/backtrace-rs/issues/285>.
> Update backtrace to v0.3.44

- src/auditor.rs
- src/commands/audit/fix.rs
- src/lib.rs
- src/lockfile.rs
Ensures changes to Cargo.toml are applied to Cargo.lock after the `fix` command has been run.
> Regenerate lockfile after `cargo audit fix`

- .github/workflows/rust.yml
- audit.toml.example
- src/commands/audit.rs
- src/config.rs
- src/presenter.rs
Dependent on modifications in rustsec (https://github.com/RustSec/rustsec-crate/pull/156)
========
This is an initial attempt at #195 that I'm hoping for some feedback on.
I erred towards not modifying the `rustsec` crate in the approach here because I wasn't sure about the crates that depend on `rustsec`, but I think it could be cleaner to do some work there, such as:
- have the `Report` struct have something like a `WarningInfo` struct (to replace the `Vec<Warning>`)
- have the `WarningInfo` struct essentially be a hashmap of `warning::Type` to `Vec<Warning>`
- modify `Warning` and/or `warning::Type` to better support the hashmap of warning types to lists of warnings; e.g. maybe ideally `warning::Type` enum (or something like it) would not hold data
> specify deny-warning types

- .github/workflows/rust.yml
- Cargo.lock
Applies `cargo update` and includes some minor tweaks to get CI passing again:
- Ignores `RUSTSEC-2020-0016` (net2 being unmaintained)
- Runs clippy against MSRV (1.40.0) to avoid new clippy lints breaking future builds (until we bump MSRV)
> Cargo.lock: update dependencies; fix build

- .github/workflows/rust.yml
This is a deprecation notice for the `failure` crate.
It was widely used, so it will probably be awhile before it's removed from all of our transitive dependencies.
> .github: ignore RUSTSEC-2020-0036 in self-audit

- Cargo.lock
- Cargo.toml
`smol_str` crate is used in `cargo-audit` through `crates-index`. `smol_str` MSRV is current stable version of Rust, while `cargo-audit` MSRV is 1.40. This PR pins `smol_str` version to one that works with older Rust versions.
fixes #254
> pin smol_str to 0.1.16 to support Rust 1.44 or older

- Cargo.lock
- Cargo.toml
i've tried `cargo install --git https://github.com/galich/cargo-audit.git --branch move-smol-to-deps` and it was working with Rust 1.44
> move smol_str to dependencies from dev-dependencies

- src/commands.rs
I noticed that when trying to use a config file in a project/workspace directory (`projectname/.cargo/audit.toml`) `cargo-audit` didn't pick up on the configuration file. After checking the source I found that it only can use configurations from the users home directory, which imo is slightly prohibitive in the situations you can use it for. For example, it would be difficult to have a work `cargo-audit` configuration that may be more strict compared to one for your hobby projects.  
The order I chose for checking for config directories (I added a code comment as well about it) is:
1. The project specific cargo configuration directory
2. The user's home directory located configuration. 
I went for this approach because [it lines up with how cargo itself searches for …
> Add support for project specific config directories

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- README.md
- src/auditor.rs
- src/commands/audit/fix.rs
- src/presenter.rs
- tests/acceptance.rs
This reverts commit e369d15194b54dd8a8155c332720cd73b0cbb97b.
This upgrade caused breaking changes to the JSON format.
Will try again with a less aggressive upgrade.
> Revert "Bump `rustsec` crate to v0.22; MSRV 1.41+"

- Cargo.lock
- Cargo.toml
- src/auditor.rs
- src/presenter.rs
Re-attempt at #271, with less invasive/breaking changes to the JSON report format.
> Bump `rustsec` crate to v0.22.2

- audit.toml.example
- src/commands/audit.rs
- src/config.rs
- src/presenter.rs
Changing `--deny-warnings` to take an argument is a breaking change that might catch people off guard.
This splits the parameterized `-D`/`--deny` from `--deny-warnings`, marking the latter as legacy and itself spitting out a warning.
This also aligns the "deny all warnings" option to be `-D warnings` or `--deny warnings` ala other Rust tooling (e.g. RUSTFLAGS/clippy).
> Split `-D`/`--deny` and `--deny-warnings`

- Cargo.lock
- bump byteorder from 1.4.2 to 1.4.3
- bump regex from 1.4.3 to 1.4.4
(This also drops the dependency on thread_local.)
- bump regex-syntax from 0.6.22 to 0.6.23
- bump security-framework from 2.1.1 to 2.1.2
- bump syn from 1.0.62 to 1.0.63
- bump tracing-attributes from 0.1.13 to 0.1.14
> Cargo.lock: bump various dependencies

- .github/workflows/release.yml
Submitted for consideration re #66
Obviously not end-to-end tested against this repo.
Some choices/questions:
- I've named the Windows and macOS sections with their isa (x86-64) even though that's currently the only option, in the optic that perhaps there would eventually be builds for Windows ARM or Apple Silicon.
- I've selected tar.gz as the archive format (zip on windows) as it's most common but it could be xz or zstd... as you wish
- I've included the readme, changelog, and license files in the archive. Maybe that's not necessary? Or should the audit.toml.example file be included as well for even more of a batteries-included ux?
- Should the build be done with `--locked` to respect the lockfile?
- Should checksums be generated? (not sure how to do that due to the job layout / …
> Generate release builds with github actions

- Cargo.lock
* Removing arrayref v0.3.6
* Removing arrayvec v0.5.2
* Updating backtrace v0.3.56 -> v0.3.57
* Removing blake2b_simd v0.5.11
* Removing constant_time_eq v0.1.5
* Updating crates-index v0.16.3 -> v0.16.5
* Removing crossbeam-utils v0.8.3
* Updating dirs v3.0.1 -> v3.0.2
* Updating dirs-sys v0.3.5 -> v0.3.6
* Updating futures-channel v0.3.13 -> v0.3.14
* Updating futures-core v0.3.13 -> v0.3.14
* Updating futures-io v0.3.13 -> v0.3.14
* Updating futures-sink v0.3.13 -> v0.3.14
* Updating futures-task v0.3.13 -> v0.3.14
* Updating futures-util v0.3.13 -> v0.3.14
* Removing getrandom v0.1.16
* Updating git2 v0.13.17 -> v0.13.18
* Updating http v0.2.3 -> v0.2.4
* Updating httparse v1.3.5 -> v1.4.0
* Updating idna v0.2.2 -> v0.2.3
* Updating jobserver v0.1.21 -> v0.1.22
* Updating js-sys …
> Cargo.lock: update several dependencies

- .github/workflows/admin.yml
- .github/workflows/cargo-audit.yml
- .github/workflows/cargo-lock.yml
- .github/workflows/cvss.yml
- .github/workflows/platforms.yml
- .github/workflows/rustsec.yml
Avoids running all workflows on all changes, instead running workflows for PRs that change files that could cause breakages.
The `push` triggers are still unconditional, meaning if a change does cause a breakage and this behavior masks it, it will still be caught after merge.
> CI: gate workflow execution for PRs on changed files

- cargo-audit/src/auditor.rs
- cargo-audit/src/commands/audit.rs
- cargo-audit/src/commands/audit/fix.rs
- cargo-audit/src/lockfile.rs
- cargo-audit/tests/acceptance.rs
- cargo-audit/tests/support/empty/README
- rustsec/src/error.rs
Use a new exit status (2) when an error is triggered (e.g., when finding or parsing the lockfile). Update the audit() and generate() definitions to propagate the error.
`crate::error` does not provide a convenient constructor. It is also not used elsewhere. Instead, rely on `rustsec::error` to build the error.
> Add new exit status for errors

- Cargo.lock
- admin/CHANGELOG.md
- admin/Cargo.toml
- Use crates index instead of crates.io api ([#372])
[#372]: https://github.com/RustSec/rustsec/pull/372
> rustsec-admin v0.4.3

- Cargo.lock
- cargo-lock/CHANGELOG.md
- cargo-lock/Cargo.toml
- cargo-lock/src/lib.rs
- rustsec/Cargo.toml
- Support for V3 lockfile format ([#363])
- Bump `semver` to v1.0.0 ([#378])
[#363]: https://github.com/RustSec/rustsec/pull/363
[#378]: https://github.com/RustSec/rustsec/pull/378
> cargo-lock v7.0.0

- Cargo.lock
- admin/CHANGELOG.md
- admin/Cargo.toml
- OSV export ([#366])
- Bump `rustsec` to v0.24.0 ([#388])
[#366]: https://github.com/RustSec/rustsec/pull/366
[#388]: https://github.com/RustSec/rustsec/pull/388
> rustsec-admin v0.5.0

- Cargo.lock
- cargo-audit/CHANGELOG.md
- cargo-audit/Cargo.toml
- cargo-audit/src/lib.rs
- New exit status (2) for Cargo.lock parsing errors ([#368])
- Bump `rustsec` crate dependency to v0.24 ([#388])
[#368]: https://github.com/RustSec/cargo-audit/pull/368
[#388]: https://github.com/RustSec/cargo-audit/pull/388
> cargo-audit v0.15.0

- rustsec/src/advisory/linter.rs
The year part of a CVE ID may be different from the reported year as discovered in RustSec/advisory-db#946. This PR softens the linting for CVE IDs as suggested in the [comment](https://github.com/RustSec/advisory-db/pull/946#issuecomment-872698576).
> Do not lint year in CVE IDs

- Cargo.lock
- rustsec/CHANGELOG.md
- rustsec/Cargo.toml
- rustsec/src/lib.rs
- Do not lint year in CVE IDs ([#393])
[#393]: https://github.com/RustSec/rustsec-crate/pull/393
> rustsec v0.24.1

- Cargo.lock
- admin/CHANGELOG.md
- admin/Cargo.toml
- Bump `rustsec` to v0.24.1 ([#394])
[#394]: https://github.com/RustSec/rustsec/pull/394
> rustsec-admin v0.5.1

- Cargo.lock
- cargo-lock/CHANGELOG.md
- cargo-lock/Cargo.toml
- cargo-lock/src/lib.rs
- Bump `petgraph` dependency from 0.5.1 to 0.6.0 ([#396])
[#396]: https://github.com/RustSec/rustsec/pull/396
> cargo-lock v7.0.1

- cvss/src/v3/base.rs
- cvss/tests/base.rs
'no impact' => all of C, I, A are set to N
Two changes were needed:
1) the call to .abs() lead to a non negative  iss_scoped score 
in the problematic case, removed that call
2) the iss_scoped needs to be inferior or equal to 0   for the
resulting score to be set to 0,
else the exploitability gets factored in for the final score
This is  my first ever pull request, Sorry if I missed something! 
Thanks
> Proposed fix for #398 

- rustsec/src/osv/unaffected_range.rs
* Add support for `~` operator in version requirements, add tests
* Add support for `=` operator in version requirements, add tests
* Make `^` operator handling spec-compliant, add tests. The spec discrepancy doesn't seem to affect the current DB data.
After this is merged, if we use `~` requirements in the DB, that will work on both very old cargo-audit versions and very new ones, but version 0.15.0 exactly will be broken (it's the only released version with rustsec v0.24 before these changes)
> Support ~ and = operators in version specification

- Cargo.lock
- rustsec/CHANGELOG.md
- rustsec/Cargo.toml
- rustsec/src/lib.rs
- Support `~` and `=` operators in version specification ([#402])
- Bump `crates-index` from 0.16.7 to 0.17.0 ([#403])
[#402]: https://github.com/RustSec/rustsec-crate/pull/402
[#403]: https://github.com/RustSec/rustsec-crate/pull/403
> rustsec v0.24.2

- rustsec/CHANGELOG.md
Now that the `rustsec` crate has been integrated into the monorepo, the old links to PRs are no longer valid.
This commit fixes the valid ones, and removes the defunct ones.
> rustsec: fix dead links in CHANGELOG.md

- rustsec/src/osv/osv_advisory.rs
Mirror the changes done in https://github.com/ossf/osv-schema/pull/1
Marking this as draft because OSV upstream is not yet prepared to pull in v0.8, but I believe the code on our side is complete.
I have raised some concerns about the v0.8 changes privately, but they mostly concern parsing and various edge cases we don't exercise, so future revisions are unlikely to affect us.
~~Curiously, the new structure lets us also encode the version ranges we've put on affected functions. I'm not sure it's a good idea to keep those around - but now if we want to, we can!~~
> Support OSV v0.8

- Cargo.lock
- cargo-audit/CHANGELOG.md
- cargo-audit/Cargo.toml
- cargo-audit/src/lib.rs
- Pin `thiserror` and `zeroize` to avoid MSRV breakages ([#415])
[#415]: https://github.com/rustsec/rustsec/pull/415/
> cargo-audit v0.15.1

- cargo-audit/Cargo.toml
- rustsec/Cargo.toml
> cargo-audit+rustsec: add `vendored-libgit2` feature

- Cargo.lock
- cargo-audit/Cargo.toml
- rustsec/CHANGELOG.md
- rustsec/Cargo.toml
- rustsec/src/lib.rs
- `vendored-libgit2` feature ([#432])
- OSV v0.8 ([#421])
[#421]: https://github.com/RustSec/rustsec/pull/421
[#432]: https://github.com/RustSec/rustsec/pull/432
> rustsec v0.24.3

- Cargo.lock
- cargo-audit/CHANGELOG.md
- cargo-audit/Cargo.toml
- cargo-audit/src/lib.rs
- `vendored-libgit2` feature ([#432])
[#432]: https://github.com/rustsec/rustsec/pull/432
> cargo-audit v0.15.2

- cargo-audit/src/commands/audit.rs
Currently, `cargo audit --color=auto` (which the `--help` says is the default option) causes a panic. This PR fixes that.
> Parse --color=auto correctly

- Cargo.lock
- admin/Cargo.toml
- admin/src/web/mod.rs
Opened over https://github.com/rustsec/rustsec/pull/425
This bumps the dependency and fixes it for the breaking API change.
> Bump rust-embed from 5.9.0 to 6.2.0

- rustsec/src/advisory/id.rs
relevant for `rustsec-admin web`
Right now GHSA IDs are not clickable, unlike CVE IDs: https://rustsec.org/advisories/RUSTSEC-2019-0035.html
This PR fixes that.
> Map GHSA IDs to relevant URLs

- cargo-audit/README.md
> README: Add packaging status for cargo-audit

- .github/workflows/release.yml
This may relate to why the action failed. The prior index extracted `cargo-audit` instead of the version. Relates to #66
> ci: extract version

- .github/workflows/release.yml
Same thing as in #445. These are not the cause of the binaries failing to be archived. The cause is path confusion between the actions-rs/cargo compile step and the packaging step. I will submit another PR for that
> ci: fix other extract version uses

- .github/workflows/release.yml
This ensures the archive steps put the compressed file where the github
release step can find it.
I also removed the `set -eux` flag because GitHub actions initialize
bash with the appropriate [flags and options](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#using-a-specific-shell).
They do not use `-x` but I feel that is only of value for debugging and
so should not be included for the stable release workflow.
Relates to #66.
> ci: ensure release workflow finds archives

- Cargo.lock
- rustsec/Cargo.toml
Pinning makes the dependency graph brittle and hard to integrate with
other crates and their dependencies.
As far as MSRV goes, `thiserror` seems like a non-issue since it has always had an MSRV of 1.31.
`smol_str` is no longer needed so can be removed.
> Unpin thiserror and smol_str

- .github/workflows/cargo-audit.yml
- .github/workflows/cargo-lock.yml
- .github/workflows/rustsec.yml
- .github/workflows/workspace.yml
- cargo-audit/README.md
- cargo-lock/README.md
- cargo-lock/src/package/source.rs
- rustsec/README.md
- rustsec/src/advisory/informational.rs
- rustsec/src/advisory/linter.rs
- rustsec/src/database/scope.rs
This makes it possible to merge #439 upgrading `cargo-edit` to v0.8.0
> Bump MSRV to 1.47

- admin/src/assigner.rs
- rustsec/src/advisory/id.rs
Fixes the newly-introduced `clippy::upper_case_acronyms` lint by following standard Rust capitalization conventions, changing the all upper case names to ones which capitalize only the first letter, e.g.
- `advisory::id::Kind::RUSTSEC` => `advisory::id::Kind::RustSec`
- `advisory::id::Kind::CVE` => `advisory::id::Kind::CVE`
...
> rustsec: make `advisory::id::Kind` lowercase

- Cargo.lock
- platforms/Cargo.toml
- platforms/src/lib.rs
- platforms/src/platform/tier1.rs
- platforms/src/platform/tier2.rs
- platforms/src/platform/tier3.rs
- platforms/src/target/arch.rs
- platforms/src/target/env.rs
- rustsec/Cargo.toml
Changes the `target::Arch` and `target::Env` enums to have variants which pass the `clippy::upper_case_acronyms` lint, replacing all upper case letters with the standard Rust enum capitalization.
> platforms: follow `upper_case_acronyms` conventions

- .github/workflows/cargo-audit.yml
These are routinely the slowest builds and annoying when trying to iterate on multiple PRs in a row.
This temporarily disables them, with the goal of re-enabling them prior to the next release.
> cargo-audit: temporarily disable macOS CI

- cargo-audit/src/config.rs
- rustsec/src/advisory/date.rs
- rustsec/src/advisory/id.rs
- rustsec/src/osv/osv_advisory.rs
- rustsec/src/repository/git/authentication.rs
In preparation for bumping MSRV to 1.52, this commit fixes all of the clippy nits presently surfaced by the version included with the Rust 1.52 distribution.
> Clippy fixes for 1.52

- .github/workflows/cargo-audit.yml
- .github/workflows/rustsec.yml
- .github/workflows/workspace.yml
- cargo-audit/README.md
- rustsec/README.md
- rustsec/src/osv/osv_advisory.rs
This makes it possible to merge #439 upgrading `cargo-edit` to v0.8.0
Note: MSRV was previously bumped to 1.47 in #469 in pursuit of the same goal, but it turns out this was not the correct MSRV.
> Bump MSRV to 1.52

- .cargo/audit.toml
Removes all vulns patched by the `cargo-edit` upgrade from the allowed list in audit.toml
> .cargo/audit.toml: remove patched vulns

- Cargo.lock
- admin/Cargo.toml
- cargo-audit/Cargo.toml
- rustsec/CHANGELOG.md
- rustsec/Cargo.toml
- rustsec/src/lib.rs
- Bump `cargo-edit` dependency from 0.7.0 to 0.8.0 ([#439])
- Make `advisory::id::Kind` lowercase ([#471])
- Bump MSRV to 1.52 ([#476])
- Flatten API: make modules with one type non-`pub`; re-export type from parent ([#478])
[#439]: https://github.com/RustSec/rustsec/pull/439
[#471]: https://github.com/RustSec/rustsec/pull/471
[#476]: https://github.com/RustSec/rustsec/pull/476
[#478]: https://github.com/RustSec/rustsec/pull/478
> rustsec v0.25.0

- Cargo.lock
- admin/Cargo.toml
- admin/src/web.rs
We must not escape the html as it is done automatically by atom_syndication now.
> Update atom_syndication to 0.11

- Cargo.lock
- admin/CHANGELOG.md
- admin/Cargo.toml
- admin/README.md
- Update `rustsec` crate to v0.25 ([#480])
- Update `atom_syndication` to 0.11 ([#481])
[#480]: https://github.com/RustSec/rustsec/pull/480
[#481]: https://github.com/RustSec/rustsec/pull/481
> rustsec-admin v0.6.0

- Cargo.lock
- platforms/CHANGELOG.md
- platforms/Cargo.toml
- rustsec/Cargo.toml
- New tier 3 targets ([#357])
- Sync with Rust platform support documentation ([#353])
- Follow `upper_case_acronyms` conventions ([#473])
- Make tier modules non-`pub` ([#483])
- Make `Platform::ALL` an inherent constant ([#484])
[#353]: https://github.com/rustsec/rustsec/pull/353
[#357]: https://github.com/rustsec/rustsec/pull/357
[#473]: https://github.com/rustsec/rustsec/pull/473
[#483]: https://github.com/rustsec/rustsec/pull/483
[#484]: https://github.com/rustsec/rustsec/pull/484
> platforms v2.0.0

- Cargo.lock
- rustsec/CHANGELOG.md
- rustsec/Cargo.toml
- rustsec/src/lib.rs
- Bump `platforms` dependency to v2.0.0 ([#485])
[#485]: https://github.com/RustSec/rustsec/pull/485
> rustsec v0.25.1

- .github/workflows/cargo-audit.yml
- Cargo.lock
- cargo-audit/CHANGELOG.md
- cargo-audit/Cargo.toml
- cargo-audit/src/lib.rs
- Bump `rustsec` dependency to v0.25; MSRV 1.52 ([#480])
- Parse `--color=auto` correctly ([#436])
[#436]: https://github.com/rustsec/rustsec/pull/436
[#480]: https://github.com/rustsec/rustsec/pull/480
> cargo-audit v0.16.0

- Cargo.lock
Adds compatibility with LibreSSL 3.4.x.
> Update openssl-sys to 0.9.72

- Cargo.lock
- cargo-audit/Cargo.toml
- cargo-audit/tests/acceptance.rs
This pull request removes unused lazy_static from dependencies in cargo-audit and updates doc comment in its tests.
> cargo-audit: remove unused lazy_static from dependencies

- rustsec/src/fixer.rs
The `cargo-edit` crate had a behaviour change that now requires the absolute path to the toml file. 
Otherwise cargo-audit will panic with the message "Absolute path needed, got: ".
For the record, an example of the panic:
```
The application panicked (crashed).
Message:  Absolute path needed, got: 
Location: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-edit-0.8.0/src/dependency.rs:199
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
(7 post panic frames hidden)                          
7: cargo_edit::dependency::Dependency::to_toml::had52f650d1c415e3
at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-edit-0.8.0/src/dependency.rs:199
8: …
```
> rustsec: fix the fixer function in the `cargo-audit`

- Cargo.lock
- Cargo.toml
- admin/Cargo.toml
- admin/src/application.rs
- admin/src/commands.rs
- admin/src/commands/assign_id.rs
- admin/src/commands/lint.rs
- admin/src/commands/list_affected_versions.rs
- admin/src/commands/osv.rs
- admin/src/commands/version.rs
- admin/src/commands/web.rs
- admin/src/web.rs
- cargo-audit/Cargo.toml
- cargo-audit/src/application.rs
- cargo-audit/src/commands.rs
- cargo-audit/src/commands/audit.rs
- cargo-audit/src/commands/audit/fix.rs
- platforms/src/error.rs
- rustsec/src/advisory/linter.rs
This is a relatively large pull request that upgrades all the dependencies to their latest version. Due to breaking changes in the `abscissa_core` crate, a lot of framework-related changes are made.
The changes could be summarized as follows:
- Use `clap` instead of `gumdrop`. `abscissa_core` no longer bundles a command-line parser, and the upstream project recommends `clap` 3.x for this task.
- As a result of the last change, the command-line parser has been rewritten. To make `clap` happy, a new parsing error was added in `platforms/src/error.rs`
- The base framework has been adapted to the new structure in `abscissa_core`.
- Fixed some reference passing issues in `admin/src/web.rs`.
> tree-wide: update all the dependencies

- platforms/platforms-data-gen/templates/arch_footer.rs
- platforms/platforms-data-gen/templates/bits_footer.rs
- platforms/platforms-data-gen/templates/endian_footer.rs
- platforms/platforms-data-gen/templates/env_footer.rs
- platforms/platforms-data-gen/templates/os_footer.rs
- platforms/src/platform/tier.rs
- platforms/src/target/arch.rs
- platforms/src/target/endian.rs
- platforms/src/target/env.rs
- platforms/src/target/os.rs
- platforms/src/target/pointerwidth.rs
Closes #493 and #492
Deserializes into an owned `String` type, which allows deserialization in cases where a `&str` can't be borrowed.
> platforms: use owned `String` for serde deserializers

- Cargo.lock
- platforms/CHANGELOG.md
- platforms/Cargo.toml
- platforms/README.md
- platforms/src/error.rs
- platforms/src/lib.rs
- rustsec/Cargo.toml
- `target_endian` and `target_pointer_width` fields on `Platform` ([#516])
- Auto-generate platforms registry from rustc ([#516])
- Make `Platform` struct `#[non_exhaustive]` to allow new fields ([#516])
- Make `Platform::env` field non-optional ([#516])
- `serde` deserializers ([#527])
[#516]: https://github.com/rustsec/rustsec/pull/516
[#527]: https://github.com/rustsec/rustsec/pull/527
> platforms v3.0.0

- cargo-audit/src/application.rs
- cargo-audit/src/bin/cargo-audit/main.rs
- cargo-audit/src/commands/audit.rs
- cargo-audit/src/commands/audit/fix.rs
- cargo-audit/src/prelude.rs
Removes legacy accessor functions and accesses application state through the `APP` constant exclusively, which matches the upstream Abscissa application boilerplate.
> cargo-audit: Abscissa v0.6 cleanups

- cargo-lock/src/package/source.rs
Adds a default `SourceId` (i.e. crates.io):
`registry+https://github.com/rust-lang/crates.io-index`
> cargo-lock: add `SourceId::default()`

- Cargo.lock
- cargo-lock/CHANGELOG.md
- cargo-lock/Cargo.toml
- cargo-lock/LICENSE-MIT
- cargo-lock/src/lib.rs
- `SourceId::default()` ([#536])
- MSRV is now 1.49 ([#524])
- V3 lockfile handling and tests ([#535])
[#524]: https://github.com/RustSec/rustsec/pull/524
[#535]: https://github.com/RustSec/rustsec/pull/535
[#536]: https://github.com/RustSec/rustsec/pull/536
> cargo-lock v7.1.0

- rustsec/Cargo.toml
- rustsec/README.md
- rustsec/src/advisory/versions.rs
- rustsec/src/collection.rs
- rustsec/src/lib.rs
- rustsec/src/osv.rs
- rustsec/src/osv/osv_advisory.rs
- rustsec/src/osv/osv_range.rs
- rustsec/src/osv/ranges_for_advisory.rs
- rustsec/src/osv/unaffected_range.rs
- rustsec/src/repository/git/repository.rs
- Bumps `edition` to 2021
- Sets `rust-version` to 1.57
- Removes explicit `TryFrom`/`TryInto` imports
- Uses README.md as the toplevel rustdoc
- Gets rustdoc building clean again
> rustsec: update to 2021 edition

- rustsec/src/database/query.rs
The RustSec Advisory Database contains advisories for both crates and rustc releases, exposing them both programatically.
However, most downstream users are interested only in crate advisories. The rustc advisories, which are versioned according to rustc releases as opposed to the corresponding crate versions, may lead to surprising and unexpected false positives if users don't select the appropriate scope.
Therefore, `Query::crate_scope()` seems like a more appropriate `Default`.
See deps-rs/deps.rs#97 for a real-world example of where this caused unexpected false positives.
> rustsec: use `Query::crate_scope()` as the `Default`

- cargo-audit/src/commands/audit.rs
The replacement is `--deny warnings` which better follows conventions for Rust CLI tools.
> cargo-audit: remove deprecated `--deny-warnings` CLI option

- cvss/src/lib.rs
- cvss/src/v3.rs
- cvss/src/v3/base.rs
- rustsec/tests/advisories.rs
Removes `pub` from all modules which contain only one type which is re-exported through the parent module.
> cvss: flattens module structure

- cvss/Cargo.toml
- cvss/src/error.rs
- cvss/src/lib.rs
- cvss/src/metric.rs
- cvss/src/severity.rs
- cvss/src/v3/base.rs
- cvss/src/v3/base/a.rs
- cvss/src/v3/base/ac.rs
- cvss/src/v3/base/av.rs
- cvss/src/v3/base/c.rs
- cvss/src/v3/base/i.rs
- cvss/src/v3/base/pr.rs
- cvss/src/v3/base/s.rs
- cvss/src/v3/base/ui.rs
- cvss/src/v3/score.rs
- cvss/tests/base.rs
Adds a `std` feature along with a `no_std`-friendly profile (with a hard dependency on `alloc`).
Also adds annotations to use the `doc_cfg` feature on docs.rs.
> cvss: `no_std` support

- cargo-lock/src/package.rs
- cargo-lock/src/package/source.rs
Makes an enum over various types of package sources part of the public API of this crate.
Also adds a `SourceId::kind` getter method.
> cargo-lock: expose `package::SourceKind`

- Cargo.lock
- cargo-audit/src/auditor.rs
- cargo-lock/Cargo.toml
- cargo-lock/README.md
- cargo-lock/src/lib.rs
- cargo-lock/src/lockfile/encoding.rs
- cargo-lock/src/metadata.rs
- cargo-lock/src/package.rs
- cargo-lock/src/package/checksum.rs
- cargo-lock/tests/lockfile.rs
- rustsec/Cargo.toml
- rustsec/src/database.rs
- rustsec/src/lib.rs
- rustsec/src/report.rs
- rustsec/tests/integration.rs
Removes superfluous modules (e.g. ones which contain only one type) from the public API, re-exporting such types from the parent module. This makes the API easier to browse via rustdoc.
This is a breaking change, so the version is bumped to v8.0.0-pre.
> cargo-lock: flatten API

- cargo-audit/src/error.rs
- cargo-lock/src/error.rs
- cargo-lock/src/lib.rs
- cargo-lock/src/lockfile.rs
- cargo-lock/src/lockfile/encoding.rs
- cargo-lock/src/lockfile/version.rs
- cargo-lock/src/metadata.rs
- cargo-lock/src/package/checksum.rs
- cargo-lock/src/package/source.rs
- Consolidates the `Error` and `ErrorKind` types.
- Replaces macros with plain Rust literals.
- Preserves `semver::Error` when reporting `Error::Version`.
- Marks `Error` enum as `#[non_exhaustive]`.
> cargo-lock: refactor error handling

- Cargo.lock
- cargo-lock/CHANGELOG.md
- cargo-lock/Cargo.toml
- rustsec/Cargo.toml
- Expose `package::SourceKind` ([#557])
- Flatten API ([#558])
- 2021 edition upgrade; MSRV 1.56 ([#559])
- Refactor error handling ([#560])
[#557]: https://github.com/RustSec/rustsec/pull/557
[#558]: https://github.com/RustSec/rustsec/pull/558
[#559]: https://github.com/RustSec/rustsec/pull/559
[#560]: https://github.com/RustSec/rustsec/pull/560
> cargo-lock v8.0.0

- Cargo.lock
- cargo-lock/CHANGELOG.md
- cargo-lock/Cargo.toml
- cargo-lock/src/lockfile/encoding.rs
- Dependency source extraction for V2+ lockfiles ([#568])
[#568]: https://github.com/RustSec/rustsec/pull/568
> cargo-lock v8.0.1

- cargo-audit/src/presenter.rs
- Indent fewer spaces between vulnerability field names and values
- Add a newline after "Dependency tree:"
> cargo-audit: terminal output fixups

- rustsec/Cargo.toml
- rustsec/src/error.rs
- rustsec/src/fixer.rs
- rustsec/src/lib.rs
- rustsec/src/osv.rs
- rustsec/src/osv/advisory.rs
- rustsec/src/osv/range.rs
- rustsec/src/osv/ranges_for_advisory.rs
- rustsec/src/report.rs
- rustsec/src/repository/git.rs
- rustsec/src/repository/git/authentication.rs
- rustsec/src/repository/git/commit.rs
- rustsec/src/repository/git/gitpath.rs
- rustsec/src/repository/git/modification_time.rs
- rustsec/src/repository/git/repository.rs
Adds information about what cargo features must be enabled in order for various types to be available.
This is a nightly-only feature, but fortunately docs.rs uses nightly to build documentation, so we can take advantage of it.
> rustsec: add `doc_cfg` annotations when building on docs.rs

- cargo-audit/src/auditor.rs
- cargo-audit/src/config.rs
- cargo-audit/src/presenter.rs
- rustsec/src/advisory/informational.rs
- rustsec/src/lib.rs
- rustsec/src/registry.rs
- rustsec/src/report.rs
- rustsec/src/warning.rs
- Makes `warnings` non-`pub`
- Exports the former `warning::Kind` as `WarningKind`
- Begins extracting yanked crate checks into the `rustsec` crate
> rustsec: flatten `warnings` module; rename `WarningKind`

- admin/src/assigner.rs
- rustsec/src/advisory.rs
- rustsec/src/advisory/id.rs
Like #572, flattens the `advisory::id` module, making it non-`pub` and exporting the former `id::Kind` as `IdKind`.
> rustsec: flatten `advisory::id` module; rename `IdKind`

- Cargo.lock
- admin/Cargo.toml
- cargo-audit/Cargo.toml
- rustsec/CHANGELOG.md
- rustsec/Cargo.toml
- `[advisory.source]` ([#541])
- `doc_cfg` annotations when building on docs.rs ([#571])
- Bump `git2` dependency to v0.14; MSRV 1.57 ([#524])
- Bump `platforms` dependency to v3.0 ([#532])
- Update to 2021 edition ([#538])
- Use `Query::crate_scope()` as the `Default` ([#544])
- Bump `cvss` dependency to v2.0 ([#550])
- Bump `cargo-lock` dependency to v8.0 ([#561])
- Flatten `warnings` module; rename `WarningKind` ([#572])
- Flatten `advisory::id` module; rename `IdKind` ([#573])
- Legacy database scopes ([#541])
[#524]: https://github.com/RustSec/rustsec/pull/524
[#532]: https://github.com/RustSec/rustsec/pull/532
[#538]: https://github.com/RustSec/rustsec/pull/538
[#541]: https://github.com/RustSec/rustsec/pull/541
[#544]: https://github.com/RustSec/rustsec/pull/544
[#550]: …
> rustsec v0.26.0

- Cargo.lock
- admin/CHANGELOG.md
- admin/Cargo.toml
- Update Abscissa to 0.6; replace `gumdrop` with `clap` v3 ([#525])
- Update `rustsec` crate to v0.26 ([#574])
[#525]: https://github.com/RustSec/rustsec/pull/525
[#574]: https://github.com/RustSec/rustsec/pull/574
> rustsec-admin v0.7.0

- Cargo.lock
- cargo-audit/CHANGELOG.md
- cargo-audit/Cargo.toml
- Update Abscissa to 0.6; replace `gumdrop` with `clap` v3 ([#525])
- 2021 edition upgrade ([#539])
- MSRV 1.57 ([#539], [#574])
- Bump `rustsec` to v0.26 ([#574])
- Terminal output fixups ([#570])
- Unused `lazy_static` from dependencies ([#500])
- Deprecated `--deny-warnings` CLI option ([#545])
[#500]: https://github.com/rustsec/rustsec/pull/500
[#525]: https://github.com/rustsec/rustsec/pull/525
[#539]: https://github.com/rustsec/rustsec/pull/539
[#545]: https://github.com/rustsec/rustsec/pull/54qgq5
[#570]: https://github.com/rustsec/rustsec/pull/570
[#574]: https://github.com/rustsec/rustsec/pull/574
> cargo-audit v0.17.0

- Cargo.lock
- cargo-lock/CHANGELOG.md
- cargo-lock/Cargo.toml
- Re-export `GitReference` ([#595])
- Encode version into V3 lockfiles ([#596])
[#595]: https://github.com/RustSec/rustsec/pull/595
[#596]: https://github.com/RustSec/rustsec/pull/596
> cargo-lock v8.0.2

- rustsec/CHANGELOG.md
- rustsec/src/advisory/linter.rs
**When I was moving http-tower to 2022**
https://github.com/rustsec/advisory-db/pull/1319
https://github.com/rustsec/advisory-db/pull/1320
Also happened here:
https://github.com/rustsec/advisory-db/pull/1310
Linter still requires **yanked = true**
`malformed content in [metadata]: Advisories with the withdrawn field must also set yanked = true`
This will only error in case where `withdrawn` has not been set when `yanked` was still set, allowing deprecation of `yanked` field
We can then remove `yanked` from all the existing advisories and then we can further take the field out from linter completely after
> Deprecate yanked

- Cargo.lock
- rustsec/CHANGELOG.md
- rustsec/Cargo.toml
- Deprecate `yanked` ([#631])
[#631]: https://github.com/RustSec/rustsec/pull/631
> rustsec v0.26.1

- rustsec/CHANGELOG.md
- rustsec/Cargo.toml
- rustsec/src/advisory/linter.rs
For some reason it didn't get tested properly that removing `yanked` works with `withdrawn` and seems I forgot to allow the field when I removed the error that also acted as whitelist -gate for the allowed metadata fields *sigh* :woman_shrugging: 
Need to add tests with test_data for all feature changes like this instead of just testing against current production data which can be later changed following the tooling change - which is prone to error - I really thought I had manually tested that ! :cry:
> Fix `withdrawn`

- Cargo.lock
- admin/Cargo.toml
Revert rustsec/rustsec#608 to see if that fixes tests
> Revert "build(deps): bump comrak from 0.13.0 to 0.14.0"

- admin/tests/acceptance.rs
Not very generic but makes the tests pass.
> Fix unexisting crate advisory in tests

- cargo-audit/README.md
@djmitche [suggested](https://github.com/actions-rs/audit-check/issues/223#issuecomment-1215962478) documentation to help cover the usage of `audit.toml` to ignore advisories, especially when running under a github action.
This is a draft of documentation that might help meet the need of future similar users.
Wording adapted from the description of https://github.com/rustsec/rustsec/issues/53
Fixes https://github.com/rustsec/rustsec/issues/650
> Add readme section about ignore

- Cargo.lock
- admin/Cargo.toml
Fixes #654 ansi_term dep
Dependency featureset was driven by it's bin and we don't need clap2 or ansi_term that matter
Gets rid of needless deps.
> Set comrak default-features false

- admin/src/web/static/css/basic.css
- admin/src/web/static/img/external-link.svg
Helps making the difference between internal and external links in the advisories, it is not always obvious.
> Add an icon after external links in advisory content

- Cargo.lock
- admin/Cargo.toml
So I got rid of one of the references to time 0.1 earlier by getting rid of clap2
But chrono still had default-features which meant it brought "oldtime"
So I got rid of that:
I specified the only feature `Clock` that we need from chrono and gets rid of the `oldtime` that brought time 0.1
For some reason chrono had `serde` feature specified but I don't see what is using it ?
The only usage of chrono is in admin/src/web.rs:
```
admin/src/web.rs:use chrono::{Date, Duration, NaiveDate, Utc};
admin/src/web.rs:    use chrono::NaiveDate;
```
I also bumped .lock to chrono 0.4.22 with update -p libc bump:
```
$ cargo update -p chrono --precise 0.4.22
Updating crates.io index
Adding android_system_properties v0.1.5
Updating chrono v0.4.20 -> v0.4.22
Adding iana-time-zone v0.1.46
Updating js-sys …
```
> Set chrono features and bump chrono to 0.4.22

- cargo-audit/audit.toml.example
- cargo-audit/src/commands.rs
- cargo-audit/src/config.rs
It took me a while to realize that the audit config can be located in the project directory as well. This PR adds some documentation for that.
> Clarify location of audit config

- rustsec/src/database.rs
macOS has an awful habit of dropping `.DS_Store` files everywhere, which breaks scanning of the advisory-db.
> I/O operation failed: failed to read directory `rustsec/crates/.DS_Store`

- cargo-audit/README.md
The previous URL worked while the branch was alive but is broken now.
> Fix `bin` screenshot URL in the README

- .github/workflows/release.yml
#718 re-added Cargo.lock and somehow CI didn't fall over, so re-enable --locked publishing.
This reverts commit e8d343beefbd49d986b51fb552984f25d12a47bd.
> Revert "Don't use --locked in release workflow to allow publishing again"

- .github/workflows/quitters.yml
- Cargo.lock
- Cargo.toml
- quitters/Cargo.toml
- quitters/examples/from_file.rs
- quitters/src/lib.rs
To be used in `cargo audit bin` for binaries built without `cargo audit`
> Add `quitters` crate

- cargo-audit/src/auditor.rs
- rustsec/src/cached_index.rs
It only complicates things and makes the type `!Sync`
> Drop interior mutability from CachedIndex

- admin/src/commands/lint.rs
- admin/src/commands/list_affected_versions.rs
- admin/src/linter.rs
- admin/src/web.rs
- admin/src/web/templates/advisories-sublist.html
- admin/src/web/templates/advisories.html
- admin/src/web/templates/advisory-content.html
- admin/src/web/templates/advisory-list-entry.html
- rustsec/src/advisory.rs
- rustsec/src/advisory/metadata.rs
- rustsec/src/repository/git/modification_time.rs
Tries to solve the ordering problem (ref. #685, #686) for the website and the atom feed.
An advisory has 3 dates:
* Reporting date, present in its metadata. This date is used for determining the year in the RustSec ID.
* Publication date, derived from the advisory file's creation date in git.
* Modification date, derived from the advisory file's modification date in git.
This changes the sorting order to use publication date on the website index and atom feed, and display it in the list.
As a consequence, the advisories in the index are not grouped by advisories year, so the grouping is removed (but seems to be way less relevant anyway as the number of advisories by year grows).
The three dates are now present in advisory details.
> Sort advisories by publication date

- Cargo.lock
- cargo-lock/CHANGELOG.md
- cargo-lock/Cargo.toml
- Encoding inconsistency when there's only one registry for all packages ([#767])
[#767]: https://github.com/RustSec/rustsec/pull/767
> cargo-lock v8.0.3

- cargo-lock/src/package/name.rs
Since `Name` already stores a `String` internally, this allows for a cheap conversion. Implementing this trait also implicitly adds `Into<String> for Name` - this is more desirable than calling `name.to_string()` (which implies an allocation) if one wants an owned `String` and can consume the `Name` anyway.
> cargo-lock: implement From<Name> for String

- .github/workflows/cargo-audit.yml
- .github/workflows/cargo-lock.yml
- .github/workflows/rustsec.yml
- .github/workflows/workspace.yml
- cargo-lock/CHANGELOG.md
- cargo-lock/Cargo.toml
- cargo-lock/README.md
- cargo-lock/src/package/source.rs
Closes #604
Signed-off-by: Robert Collins <robert.collins@cognite.com>
> Support sparse registry references in Lockfiles

- cargo-lock/src/package/source.rs
We need to do a breaking v9 release because `SourceKind` added a `SparseRegistry` variant.
Marking this enum as `non_exhaustive` means we'll be able to do future non-breaking additions in the event that Cargo adds new `SourceKind` variants upstream.
> cargo-lock: mark `SourceKind` as `#[non_exhaustive]`

- .github/workflows/cargo-audit.yml
- .github/workflows/cargo-lock.yml
- .github/workflows/rustsec.yml
- .github/workflows/workspace.yml
- cargo-audit/Cargo.toml
- cargo-audit/README.md
- cargo-lock/CHANGELOG.md
- cargo-lock/Cargo.toml
- cargo-lock/README.md
- cargo-lock/src/error.rs
- rustsec/Cargo.toml
- rustsec/README.md
Addresses a TODO.
1.60 is a particularly viral MSRV as it's not possible to have crates in a workspace that use namespaced/weak features unless all crates in the workspace are MSRV 1.60.
So, bumping this now prior to a breaking release means we'll also be futureproof for updates which use namespaced/weak features (including transitive dependencies)
> cargo-lock: use `Display` for `io::ErrorKind`; MSRV 1.60

- .github/workflows/cargo-audit.yml
It's currently failing. See #795.
This also attempts to re-enable the Windows build.
> cargo-audit: disable macOS CI for `--all-features`

- .github/workflows/cvss.yml
- cvss/Cargo.toml
- cvss/README.md
This crate's older MSRV is blocking the use of newer crates which make use of namespaced/weak feature activation:
https://github.com/rustsec/rustsec/actions/runs/3998049178/jobs/6860183561
See also: #794
> cvss: bump MSRV to 1.60

- Cargo.lock
- admin/src/web.rs
This release includes a number of deprecations.
To accomplish the upgrade, this annotates the usages with `allow(deprecated)` and adds a TODO comment for each one.
> admin: bump `chrono` to v0.4.23

- platforms/Cargo.toml
- platforms/src/platform/platforms.rs
- platforms/src/target/env.rs
- platforms/src/target/os.rs
This is our first platform removal in the 3.x series too. Time to put the semver policy to the test!
> Regenerate platforms for rustc 1.69.0-nightly

- admin/src/linter.rs
Added the advisory id to the output to help identify the advisory with the error.
Resolves #622
> Linter: Clean up crates.io package name check error

- rustsec/src/repository/git/repository.rs
Closes #629 
Removed the signature check of the latest commit which solved #629. Left other existing signature related functionality in place so as not to create an API break.
Tested manually against an altered advisory-db without a signed latest commit.
> Remove latest commit signature check

- cargo-audit/src/presenter.rs
Better formatting of the severity output in cargo audit as mentioned by @tarcieri  [here](https://github.com/rustsec/rustsec/pull/825#discussion_r1132517108).
```
Crate:     base64
Version:   0.5.1
Title:     Integer overflow leads to heap-based buffer overflow in encode_config_buf
Date:      2017-05-03
ID:        RUSTSEC-2017-0004
URL:       https://rustsec.org/advisories/RUSTSEC-2017-0004
Severity:  9.8 (critical)
Solution:  Upgrade to >=0.5.2
```
> Better the formatting of severity output

- cargo-audit/src/commands.rs
This adjusts the help usage section of `cargo-audit` to `cargo audit` instead of `cargo-audit audit`.
> fix(cargo-audit): set clap bin_name to cargo

- Cargo.lock
- admin/Cargo.toml
- rustsec/Cargo.toml
Fixes #830 
Supercedes #801 
`packed_simd_2` is similar how it's used. Can use this and gradually do something about it e.g. minify it for our purposes.
I've worked 0.9 with dependency bumps to: https://github.com/pinkforest/cargo-edit-9
crates-index also has to be bumped to 0.19 that picks up 0.16 git2
This was according to recommendation here:
- https://github.com/killercup/cargo-edit/issues/837#issuecomment-1405714199
> rustsec: Fix git2 via cargo-edit-9 fork

- cargo-audit/src/auditor.rs
- cargo-audit/src/presenter.rs
`audit()` was called by both the binary, multi binary and lockfile paths. This included a call to check for self advisories against cargo-audit.
For multi-binary this no only printed the results of self scanning multiple times but ran the checks multiple times.
Now the lockfile and binary execution paths check for self issues and print the results.
I have also combined the two older checks to a single check and message.
Tests pass but I believe there are no tests covering this.
> Fix #736 - Cargo audit self advisories repeated

- cargo-lock/src/package/source.rs
`SourceId::is_default_registry` would incorrectly report that the sparse crates.io index was not crates.io.
> Fix `is_default_registry` for sparse index

- cargo-lock/src/bin/cargo-lock/main.rs
- cargo-lock/src/dependency/tree.rs
This adds a few improvements to the `cargo-lock tree` subcommand:
1. Separates the decision of "should we print trees related to specific packages or all the roots" from the decision of "forward tree or inverse tree", giving the latter its own option (`-i`) and thereby allowing specific package selection for either forward or inverse trees.
2. Allows selecting packages by name, version, hash, or name@version-or-hash
3. Adds an option `-x` for printing "exact" information about each found dependency, in the form of either its sha256 package checksum or, if that's not found, its package source (which usually contains a precise git hash)
These changes are necessary to support a specific use-case I have, where I've got multiple versions of the same crate as a dependency and I want to …
> Various improvements to the "cargo-lock tree" subcommand

- .github/workflows/cargo-audit.yml
- .github/workflows/rustsec.yml
Workaround for rust-lang/rust#109266
This pins the docs build to MSRV, which should prevent regressions where new releases break the docs build.
> Fix docs build

- Cargo.lock
- cargo-lock/CHANGELOG.md
- cargo-lock/Cargo.toml
- Implement `From<Name>` for `String` ([#776])
- Support sparse registry references in `Lockfile`s ([#780])
- Mark `SourceKind` as `#[non_exhaustive]` ([#793])
- Use `Display` for `io::ErrorKind`; MSRV 1.60 ([#794])
- Bump `toml` to 0.7 ([#800], [#805])
- Improvements to the `cargo lock tree` subcommand ([#860])
- `Source::is_default_registry` for sparse index ([#859])
[#776]: https://github.com/RustSec/rustsec/pull/776
[#780]: https://github.com/RustSec/rustsec/pull/780
[#793]: https://github.com/RustSec/rustsec/pull/793
[#794]: https://github.com/RustSec/rustsec/pull/794
[#800]: https://github.com/RustSec/rustsec/pull/800
[#805]: https://github.com/RustSec/rustsec/pull/805
[#859]: https://github.com/RustSec/rustsec/pull/859
[#860]: https://github.com/RustSec/rustsec/pull/860
> cargo-lock v9.0.0

- .github/workflows/cargo-audit.yml
- .github/workflows/rustsec.yml
- Cargo.lock
- cargo-audit/Cargo.toml
- cargo-audit/README.md
- rustsec/Cargo.toml
- rustsec/README.md
Bumps the effective MSRV of `cargo-audit`+`rustsec` crates to 1.63.
Performs the following update:
Updating crates.io index
Updating aho-corasick v0.7.20 -> v1.0.1
Updating anyhow v1.0.68 -> v1.0.70
Updating block-buffer v0.10.3 -> v0.10.4
Updating bumpalo v3.12.0 -> v3.12.1
Updating bytes v1.3.0 -> v1.4.0
Updating camino v1.1.2 -> v1.1.4
Updating cargo-edit-9 v0.9.2 -> v0.9.3
Updating cc v1.0.78 -> v1.0.79
Updating clap v3.2.23 -> v3.2.24
Updating clap_derive v3.2.18 -> v3.2.24
Updating core-foundation-sys v0.8.3 -> v0.8.4
Updating cpufeatures v0.2.5 -> v0.2.7
Updating crossbeam-channel v0.5.6 -> v0.5.8
Updating crossbeam-deque v0.8.2 -> v0.8.3
Updating crossbeam-epoch v0.9.13 -> v0.9.14
Updating crossbeam-utils v0.8.14 -> v0.8.15
Updating cxx v1.0.87 -> v1.0.94
Updating cxx-build …
> Cargo.lock: update dependencies

- .github/workflows/cargo-audit.yml
- .github/workflows/quitters.yml
- .github/workflows/rustsec.yml
- .github/workflows/workspace.yml
- cargo-audit/tests/binary_scanning.rs
Speeds up CI by:
1. Running `cargo test` without the `--release` flag, avoiding compiling the code twice (tests are run with `cargo run` without `--release`)
1. Using the sparse index instead of fetching crates.io index via git, which would cause a regression in test performance (`gix` and its deps such as `miniz_oxide` compiled in debug mode)
The Rust toolchain is bumped to v1.71 for sparse index support but MSRV is still enforced by the `workspace` job.
> Faster CI for `cargo audit` tests

- .github/workflows/cargo-audit.yml
Reverts rustsec/rustsec#931
CI passing was misleading: the added test was simply not run.
> Revert "Re-enable self-audit"

- Cargo.lock
- rustsec/Cargo.toml
Matches the previous OpenSSL behavior and allows using `cargo-audit` in enterprise environments that intercept HTTPS
> Use OS native certificates for TLS

- Cargo.lock
- rustsec/Cargo.toml
- rustsec/src/advisory/license.rs
- rustsec/tests/advisories.rs
- rustsec/tests/support/example_advisory_v4_unknown_license.md
* We _actually_ need special serialization/deserialization to handle the `Other(_)` license case, doesn't seem possible with serde annotations.
* Also add a test case for unknown license
> Fix unknown license handling

- cargo-audit/src/auditor.rs
- rustsec/src/cached_index.rs
- rustsec/src/error.rs
Cleaning up the APIs after the addition of sparse index support in #923:
- Make `find_yanked()` automatically populate the cache
- Make `is_yanked()` private because of the performance pitfall of calling it in a loop without populating cache first.
- With it gone, there is no reason to expose `populate_cache()` publicly, so make it private too.
- Adjust `cargo-audit` code accordingly
- Slightly improve documentation
@Jake-Shadle FYI
> Foolproof API for the cached index

- rustsec/src/advisory.rs
- rustsec/src/advisory/linter.rs
- rustsec/src/cached_index.rs
- rustsec/src/error.rs
- rustsec/src/osv/advisory.rs
- rustsec/src/report.rs
- rustsec/src/repository/git.rs
- rustsec/src/repository/git/commit.rs
- rustsec/src/repository/git/commit_hash.rs
- rustsec/src/repository/git/repository.rs
`gix` bumps semver rather frequently, which will in turn make `tame-index` bump semver too. 
This change lets us avoid bumping semver in `rustsec` with every `gix` release.
> Do not leak `tame-index` and `gix` types into the public API

- cargo-audit/src/auditor.rs
- cargo-audit/src/binary_type_filter.rs
- rustsec/src/report.rs
- rustsec/src/warning.rs
At last, allows filtering warnings by binary type in addition to vulnerabilities.
> Add `affected` field to warnings for consistency with vulnerabilities

- Cargo.lock
- cargo-audit/CHANGELOG.md
- cargo-audit/Cargo.toml
- Release workflow: don't enable `fix` and `vendored-openssl` features ([#980])
[#980]: https://github.com/rustsec/rustsec/pull/980
> cargo-audit v0.18.1

- cvss/tests/base.rs
Without this I got errors like this one:
```
error[E0433]: failed to resolve: could not find `v3` in `cvss`
--> cvss/tests/base.rs:11:22
|
11 |     let base = cvss::v3::Base::from_str(cvss_for_cve_2013_1937).unwrap();
|                      ^^ could not find `v3` in `cvss`
```
Ref: https://salsa.debian.org/rust-team/debcargo-conf/-/blob/master/src/cvss/debian/patches/fix-unit-tests.patch
> make 'cargo test --no-default-features' run without errors

- rustsec/src/cached_index.rs
Fixes a performance regression when scanning multiple files. Only possible in `cargo audit bin`.
> Do not re-lookup packages that are already cached

- admin/src/web/templates/advisory-content.html
* Add link to the advisory in OSV format (on osv.dev)
* Render `references` links which were missing (merged with the `url` field)
> Additional information in advisory content

- cargo-audit/src/config.rs
- cargo-audit/src/presenter.rs
I'm not sure why `filter_map()` was used in the first place, but that fixes it.
Initially I was looking into adding tests, but unfortunately `abscissa_core::testing::CmdRunner` doesn't support settings the working directory, so I'm unsure how. Happy to take any directions though.
Fixes #991.
> Fix `deny = ["warnings"]` being ignored

- Cargo.lock
- rustsec/Cargo.toml
- rustsec/src/cached_index.rs
- rustsec/src/repository/git/modification_time.rs
- rustsec/src/repository/git/repository.rs
Fixes #1014
Not semver-breaking, `tame-index` is deliberately never leaked into the public API
> Upgrade tame index to fix RUSTSEC-2023-0064

- cargo-audit/CHANGELOG.md
- cargo-audit/Cargo.toml
Release a new `cargo audit` version so that Linux distributions would pick it up, and people who installed it through `cargo` would get a fix with a `cargo install` instead of requiring `cargo install --force`.
I think this is a good idea, but I'd like one of the other maintainers to sign off on it before I ship it.
> Cargo audit release with a fix for RUSTSEC-2023-0064

- Cargo.lock
- admin/Cargo.toml
- admin/src/error.rs
- admin/src/linter.rs
- admin/src/list_versions.rs
- admin/src/web.rs
- cargo-audit/src/config.rs
- rustsec/src/repository/git/commit.rs
This PR switches rustsec-admin to tame-index, which uses `gix`.
Originally the idea was to speed the linting which takes 3 minutes on CI, 
but as it turns out the linting itself takes only about 1s.
What can take time though is the initial clone of the crates-index. Using git2, this
was single-threaded and took about 1m50s. Now, with a single thread, it's done in 47s. With all 10 cores it's at 24s (most of which is downloading the pack).
I also enabled multi-threading and performance options to speed it up even more.
Unfortunately I don't know how effective these changes are on CI when linting advisories though.
I now see…
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, …
```
> rustsec-admin with tame-index

- admin/Cargo.toml
to avoid dealing with C dependencies
> admin: use `gix` max-performance-safe instead of max-performance

- .github/workflows/workspace.yml
The underlying issue was reported to https://github.com/EmbarkStudios/tame-index/issues/31 but doesn't happen in that repository on recent Clippy versions either.
> Update Clippy to fix useless warnings

- Cargo.lock
- admin/Cargo.toml
- admin/src/lib.rs
- admin/src/linter.rs
- admin/src/list_versions.rs
- admin/src/lock.rs
- rustsec/Cargo.toml
- rustsec/src/cached_index.rs
- rustsec/src/error.rs
- rustsec/src/repository/git/repository.rs
Switch from Git-compatible locks provided by `gix` to an interface around OS locks provided by `tame-index`. Git locks are very poorly designed, being plain lock files without even a PID written into them; so stale locks are left behind on SIGKILL or power loss with no way to recover.
Also acquire the global Cargo package lock when doing crates.io index lookups, to avoid racing with Cargo itself when fetching crates index.
Fixes #1011
> Switch from Git-compatible locks to OS locks

- cvss/src/severity.rs
This allows to use something like this:
```rust
let summaries: HashMap<Severity, usize>;
```
> feat: let `Severity` implement `Hash`

- rustsec/Cargo.toml
Does not any dependencies that aren't already in the dependency tree.
> Configure `gix` with `max-performance-safe` feature

- cargo-audit/src/auditor.rs
- cargo-audit/src/commands/audit.rs
- cargo-audit/src/commands/audit/fix.rs
- cargo-audit/src/lockfile.rs
Fixes #1050
Sadly no tests because `abscissa::Runner` does not let you set the working directory, and adding it would require not only a new Abscissa release but also a migration from Abscissa v3 to v4 in `cargo-audit`, which is non-trivial.
> Fix deadlock on missing lockfile

- admin/src/web/templates/advisory-content.html
discovered by atom feed validator: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frustsec.org%2Ffeed.xml
> fix typo html in advisory scores

- .github/workflows/cargo-lock.yml
- Cargo.lock
- cargo-audit/README.md
- cargo-lock/Cargo.toml
- cargo-lock/README.md
Updates dependencies to latest semver-compatible versions.
Bumps `cargo-lock` msrv to 1.67.
Supersedes #1044
> cargo update

- Cargo.lock
- cargo-audit/Cargo.toml
- cargo-audit/src/auditor.rs
- cargo-audit/src/commands/audit.rs
- cargo-audit/src/error.rs
Should fix #1053
I'm not proud of this code but I don't see a way to do it better.
We often operate on `rustsec`  errors without converting them to `cargo-audit` errors, so a custom formatting routine for `cargo_audit::Error` would not help much - we'd have to introduce an extra magic conversion for no apparent reason, which would be confusing. And hijacking the `Display` impl in `rustsec` seems wrong, it's library code after all.
This could also be solved with a macro, but Rust macros aren't exactly readable. It's a whole separate DSL embedded inside Rust, and I'd rather keep it simple and stupid.
> Display the chain of sources for errors in `cargo audit`

- Cargo.lock
- rustsec/CHANGELOG.md
- rustsec/Cargo.toml
> New rustsec v0.28.4 release with updated `gix` and `tame-index`

- cargo-audit/src/auditor.rs
- cargo-audit/src/binary_deps.rs
- cargo-audit/src/lockfile.rs
- rustsec/src/cached_index.rs
- rustsec/src/error.rs
As discussed in https://github.com/rustsec/rustsec/issues/1029#issuecomment-1815785981
This is a semver-compatible change because it only adds a private field and a new constructor: `rustsec::Error::with_source()`.
Note that there are many remaining cases where `Error` is constructed with `format_err!`, that stringify a source error; this PR only addresses the easy cases of the `Error::new()` calls.
> Add a `source` field to `rustsec::Error`, and use it in simple cases.

- Cargo.lock
- admin/Cargo.toml
- admin/src/osv_export.rs
- rustsec/Cargo.toml
- rustsec/src/repository/git/commit.rs
- rustsec/src/repository/git/modification_time.rs
This is the answer to https://github.com/Byron/gitoxide/issues/1216#issuecomment-1872388629 .
> gix upgrade to v0.56

- Cargo.lock
- admin/Cargo.toml
- admin/src/osv_export.rs
- rustsec/Cargo.toml
- rustsec/src/repository/git/commit.rs
- rustsec/src/repository/git/modification_time.rs
Reverts rustsec/rustsec#1081
Seems like it caused build failures, so reverting to unblock #1092
> Revert "gix upgrade to v0.56"

- .github/workflows/cargo-lock.yml
- .github/workflows/quitters.yml
- .github/workflows/rustsec.yml
- Cargo.lock
- admin/Cargo.toml
- admin/src/commands.rs
- admin/src/commands/assign_id.rs
- admin/src/commands/lint.rs
- admin/src/commands/list_affected_versions.rs
- admin/src/commands/osv.rs
- admin/src/commands/version.rs
- admin/src/commands/web.rs
- cargo-audit/Cargo.toml
- cargo-audit/README.md
- cargo-audit/src/commands.rs
- cargo-audit/src/commands/audit.rs
- cargo-audit/src/commands/audit/binary_scanning.rs
- cargo-audit/src/commands/audit/fix.rs
- cargo-audit/tests/acceptance.rs
- cargo-lock/Cargo.toml
- cargo-lock/README.md
- rustsec/Cargo.toml
- rustsec/README.md
This updates abscissa_core and clap to the current versions to get rid of a few outdated dependencies.
> Update abscissa_core and clap

- Cargo.lock
- admin/Cargo.toml
- admin/src/commands.rs
- admin/src/commands/sync.rs
- admin/src/error.rs
- admin/src/lib.rs
- admin/src/synchronizer.rs
- rustsec/src/advisory.rs
- rustsec/src/advisory/id.rs
- rustsec/src/error.rs
- rustsec/src/osv/advisory.rs
Result in https://github.com/rustsec/advisory-db/pull/1693.
Refs: https://github.com/rustsec/rustsec/issues/644
This PR implements:
* Alias id update from OSV advisories
* Listing OSV advisories we should consider importing into RustSec
The end goal is to be able to automatically open pull requests with the advisories updates and drafts from missing ones. For now I plan to run it regularly manually until we're confident with the result.
> Add a command to synchronize advisory data from osv.dev/GHSA

- .cargo/audit.toml
It has no immediate resolution due to the `fix` feature using unmaintained/out-of-date dependencies.
We're discussing what to do in #1107 and are definitely aware of the issue. This acknowledges it and allows us to move forward on other development without breaking the build.
> .cargo/audit.toml: ignore RUSTSEC-2024-0013

- cargo-audit/src/lockfile.rs
`cargo generate-lockfile` behaves like `cargo update` according to its documentation:
> This command will create the Cargo.lock lockfile for the current package or workspace. If the lockfile already exists, it will be rebuilt with the latest available version of every package.
Instead use `cargo update --workspace` that is documented as:
> Attempt to update only packages defined in the workspace. Other packages are updated only if they don’t already exist in the lockfile. This option is useful for updating Cargo.lock after you’ve changed version numbers in Cargo.toml.
I have verified that the `--workspace` option works even there is no workspace.
> Do not run `cargo update` when auditing

- Cargo.lock
- cargo-audit/Cargo.toml
- cargo-audit/src/commands/audit/fix.rs
- rustsec/Cargo.toml
- rustsec/src/error.rs
- rustsec/src/fixer.rs
- rustsec/src/lib.rs
Does away with editing `Cargo.toml`; instead runs `cargo update` behind the scenes to upgrade vulnerable versions.
Fixes  #1107 and  #1109 by ripping out `cargo-edit` which transitively depends on `libgit2-sys` and a bunch of other outdated versions.
> Rewrite `cargo audit fix`

- admin/Cargo.toml
- admin/src/web/templates/advisory-content.html
- admin/src/web/templates/advisory-list-entry.html
From https://djc.github.io/askama/filters.html:
> Note that the pipe symbol must not be surrounded by spaces; otherwise, it will be interpreted as the BitOr operator.
> Bump askama to 0.12

- Cargo.lock
- admin/Cargo.toml
- rustsec/Cargo.toml
It is failing for installations from crates.io, so this is a hotfix we need to push ASAP
> Upgrade to gix 0.60 to fix build

- Cargo.lock
- platforms/Cargo.toml
- platforms/README.md
- platforms/src/platform/platforms.rs
- platforms/src/target/arch.rs
- platforms/src/target/env.rs
- platforms/src/target/os.rs
Ran `regenerate-platforms-crate.sh`. Would be great if we can release a new version.
> chore: regenerate platform support and bump to platforms@3.4.0

- Cargo.lock
- admin/Cargo.toml
- rustsec/Cargo.toml
Cargo.lock is so many deletions because we had older `gix` pulled in by `admin` because I didn't hotfix it when `tame-index` broke semver.
> Update gix and tame-index to fix CI

- Cargo.lock
- admin/Cargo.toml
- cargo-audit/Cargo.toml
- cargo-audit/src/application.rs
- rustsec/Cargo.toml
- rustsec/src/repository/git/modification_time.rs
cargo-audit msrv is 1.70, IsTerminal stable from 1.70, drop is-terminal dep
updates gix* to 0.62, tame-index to 0.11.
cc https://github.com/rustsec/rustsec/pull/1173
> cargo-audit: remove is-terminal dep; bump gix-* to 0.62

- admin/src/web/templates/index.html
Just a small fix for a trivial typo I noticed while looking at the site.
Thanks for all the work you do here!
> Fix typo `then` -> `them` in index.html

- Cargo.lock
- cargo-audit/Cargo.toml
- cargo-audit/src/binary_deps.rs
- cargo-audit/src/binary_format.rs
- cargo-audit/src/binary_type_filter.rs
- cargo-audit/src/config.rs
Support auditing WASM files in `cargo audit bin`, either by using data embedded by `cargo auditable` or based on panic messages.
I added WASM support to `cargo auditable` in https://github.com/rust-secure-code/cargo-auditable/pull/145, and this PR enables auditing WASM blobs to make the embedded data actually useful.
> Support auditing WASM binaries

- .github/workflows/cargo-audit.yml
- .github/workflows/rustsec.yml
- .github/workflows/workspace.yml
- Cargo.lock
- admin/src/synchronizer.rs
- cargo-audit/Cargo.toml
- cargo-audit/README.md
- cargo-lock/src/lockfile.rs
- cargo-lock/src/lockfile/encoding.rs
- rustsec/Cargo.toml
- rustsec/README.md
- rustsec/src/advisory.rs
- rustsec/src/database/query.rs
- rustsec/src/osv/unaffected_range.rs
Updates the following dependencies:
Updating crates.io index
Locking 169 packages to latest compatible versions
Updating aho-corasick v1.1.2 -> v1.1.3
Updating allocator-api2 v0.2.16 -> v0.2.18
Updating anstream v0.6.11 -> v0.6.15
Updating anstyle v1.0.5 -> v1.0.8
Updating anstyle-parse v0.2.3 -> v0.2.5
Updating anstyle-query v1.0.2 -> v1.1.1
Updating anstyle-wincon v3.0.2 -> v3.0.4
Updating arc-swap v1.6.0 -> v1.7.1
Updating async-compression v0.4.6 -> v0.4.12
Adding atomic-waker v1.1.2
Updating autocfg v1.1.0 -> v1.3.0
Updating backtrace v0.3.69 -> v0.3.71 (latest: v0.3.73)
Updating basic-toml v0.1.8 -> v0.1.9
Updating bitflags v2.4.2 -> v2.6.0
Updating bstr v1.9.0 -> v1.9.1
Updating bumpalo v3.14.0 -> v3.16.0
Updating bytes v1.5.0 -> v1.6.1
Updating camino v1.1.6 -> v1.1.7
Updating cc …
> Cargo.lock: bump dependencies

- Cargo.lock
- Cargo.toml
- cargo-audit/Cargo.toml
- cargo-lock/Cargo.toml
- rustsec/Cargo.toml
Bumps the following to prerelease versions (which are not yet intended to have an associated crates.io release):
- `cargo-audit` v0.21.0-pre
- `cargo-lock` v10.0.0-pre
- `rustsec` v0.30.0-pre
> Bump versions to prepare for breaking changes

- cargo-lock/src/error.rs
- cargo-lock/src/lockfile.rs
Removes an `impl From<toml::de::Error>` for `cargo_lock::Error`, which in theory is the only place `toml` was present in `cargo-lock`'s public API.
Removing this impl should theoretically allow non-breaking upgrades to the `toml` crate in the future.
> cargo-lock: remove `toml` from the public API

- Cargo.lock
- Cargo.toml
Uses the crates.io prerelease of `cargo-lock`
> Use `cargo-lock` v10.0.0-pre.0 branch for `auditable-serde`

- Cargo.lock
- Cargo.toml
- cargo-audit/Cargo.toml
- cargo-audit/src/binary_deps.rs
These drop the dependency on `cargo-lock`.
Vendors the code removed in rust-secure-code/cargo-auditable#160 into `binary_deps.rs`
> Bump `auditable-info` => 0.8; `auditable-serde` => v0.7

- .github/workflows/cargo-audit.yml
- cargo-audit/Cargo.toml
- cargo-audit/src/binary_format.rs
It was previously marked as optional, however it's already a hard transitive dependency by way of the `rustsec` crate.
It could potentially be removed as a direct dependency since it's re-exported as `rustsec::cargo_lock` anyway, but this PR aims to immediately resolve #1238
> cargo-audit: make `cargo-lock` a hard dependency

- Cargo.lock
So that users of `cargo install --locked` would get the fix
> Bump auditable-extract in Cargo.lock for the WASM bugfix

- Cargo.lock
- Cargo.toml
Full changelog: https://github.com/iqlusioninc/abscissa/blob/main/CHANGELOG.md#080-2024-10-15
> cargo-audit: bump `abscissa` to v0.8

- cargo-lock/src/dependency.rs
- cargo-lock/src/lib.rs
Replaces the need for manual annotations
> cargo-lock: use `doc_auto_cfg`

- Cargo.lock
- Cargo.toml
- cargo-lock/CHANGELOG.md
- cargo-lock/Cargo.toml
- cargo-lock/README.md
- V4 lockfile support ([#1206])
- MSRV 1.70 ([#1092])
- `toml` dependency from public API ([#1226])
[#1092]: https://github.com/RustSec/rustsec/pull/1092
[#1206]: https://github.com/RustSec/rustsec/pull/1206
[#1226]: https://github.com/RustSec/rustsec/pull/1226
> cargo-lock v10.0.0

- Cargo.lock
- cargo-lock/CHANGELOG.md
- cargo-lock/Cargo.toml
- Remove `precise` from source IDs during normalization ([#1270])
[#1270]: https://github.com/RustSec/rustsec/pull/1270
> cargo-lock v10.0.1

- Cargo.toml
This ensures we always get the bugfix in #1270
> Cargo.toml: bump `cargo-lock` to v10.0.1

- Cargo.toml
- rustsec/CHANGELOG.md
- rustsec/Cargo.toml
- MSRV 1.73 ([#1222])
- Bump `cargo-lock` to v0.10; adds V4 lockfile support ([#1224], [#1264])
- Bump `gix` to 0.66 ([#1251])
- Bump `tame-index` to v0.14 ([#1251])
[#1222]: https://github.com/rustsec/rustsec/pull/1222
[#1224]: https://github.com/rustsec/rustsec/pull/1224
[#1251]: https://github.com/rustsec/rustsec/pull/1251
[#1264]: https://github.com/rustsec/rustsec/pull/1264
> rustsec v0.30.0

- Cargo.lock
- cargo-audit/CHANGELOG.md
- cargo-audit/Cargo.toml
- V4 lockfile support ([#1275])
- Bump `auditable-info` => 0.8; `auditable-serde` => v0.7 ([#1229])
- Bump `abscissa` to v0.8 ([#1262])
- Bump `rustsec` to v0.30; adds V4 lockfile support ([#1275])
[#1229]: https://github.com/rustsec/rustsec/pull/1229
[#1262]: https://github.com/rustsec/rustsec/pull/1262
[#1275]: https://github.com/rustsec/rustsec/pull/1275
> cargo-audit v0.21.0

- Cargo.lock
- platforms/Cargo.toml
- platforms/README.md
- platforms/src/platform/platforms.rs
- platforms/src/target/os.rs
Ran `regenerate-platforms-crate.sh` for new Rust toolchain changes. Would be great if we can release a new version.
> chore: regenerate platform support and bump to platforms@3.4.2

- admin/src/web/templates/advisory-content.html
Use the calculator at first.org (which manages the CVSS specification). It expects the full vector without modification, and is also more neutral than a US government site.
Fixes #1177.
> Fix links to CVSS calculator

- rustsec/src/osv/advisory.rs
to fix OSV JSON schema compliance https://github.com/rustsec/advisory-db/issues/2135
> Do not serialize schema version as 'null' if not set

- admin/src/commands.rs
- admin/tests/acceptance.rs
- cargo-audit/src/commands.rs
- cargo-audit/tests/acceptance.rs
Unblocks development.
These are problematic both due to `deny(warnings)` and the sheer amount of times they're emitted, drowning out all the actually useful warnings.
> Suppress useless warnings

- rustsec/tests/integration.rs
I found it very confusing that our tests assume that. I thought failing tests means the code is broken, but turns out it wasn't.
> Do not assert in tests that there are no vulnerabilities in our own Cargo.lock

- Cargo.lock
Includes `abscissa_core` and `abscissa_derive`.
Fixes stdout logging (now stderr) and includes an upstream suppression for custom derive lint warnings
> Cargo.lock: bump Abscissa to v0.8.2

- .github/workflows/cargo-audit.yml
- .github/workflows/cargo-lock.yml
- .github/workflows/cvss.yml
- .github/workflows/quitters.yml
- .github/workflows/rustsec.yml
- .github/workflows/workspace.yml
- Cargo.lock
- Cargo.toml
- cargo-audit/Cargo.toml
- cvss/Cargo.toml
- cvss/src/v3/base/ac.rs
- rustsec/Cargo.toml
- rustsec/src/repository/git/modification_time.rs
- rustsec/src/repository/git/repository.rs
An update to the latest version with minimal changes to accomplish this.
Particularly the GitModificationTime code could be simplified by using higher-level APIs, but I refrained from this as there may be a good reason not to do it that I am unaware of.
This PR was motivated by https://github.com/GitoxideLabs/gitoxide/discussions/1797 and @decathorpe.
> update `gix` to v0.70 and `tame-index` index to 0.17.

- Cargo.lock
- admin/src/assigner.rs
- rustsec/src/advisory.rs
- rustsec/src/database/entries.rs
Added a commit to update dependencies to deal with the audit failure for [RUSTSEC-2025-0009](https://rustsec.org/advisories/RUSTSEC-2025-0009).
> Introduce Advisory::is_draft() to unify logic

- .github/workflows/rustsec.yml
- .github/workflows/workspace.yml
- Cargo.lock
- rustsec/Cargo.toml
Currently, rustsec with git support is unusable in a dependency graph that also enables gix's curl feature. For example something as simple as:
```toml
[dependencies]
cargo = "0.88.0"
rustsec = "0.30.2"
```
causes `gix-transport` to fail to compile because rustsec enables gix's reqwest backend (indirectly through tame-index) and cargo enables gix's curl backend.
- https://github.com/EmbarkStudios/tame-index/blob/0.21.0/Cargo.toml#L14-L17
- https://github.com/rust-lang/cargo/blob/0.88.0/Cargo.toml#L51
```console
error[E0428]: the name `Impl` is defined multiple times
--> $CARGO_HOME/registry/src/index.crates.io-1949cf8c6b5b557f/gix-transport-0.45.0/src/client/blocking_io/http/mod.rs:220:1
|
217 | pub type Impl = curl::Curl;
| --------------------------- previous definition of the type …
```
> Make rustsec library compatible with gix's curl backend

- cargo-audit/src/commands/audit.rs
- cargo-audit/src/config.rs
- cargo-audit/src/lib.rs
- cargo-audit/src/presenter.rs
- cargo-audit/src/sarif.rs
This PR adds SARIF (Static Analysis Results Interchange Format) output support to cargo-audit, enabling direct integration with GitHub Security tab and other security analysis platforms.
Fixes #1384
> feat(cargo-audit): add SARIF output format support

- Cargo.lock
- Cargo.toml
- quitters/src/lib.rs
- rustsec/Cargo.toml
Left toml dependencies to #1389.
> Fix new warning from 1.89, update dependencies

- Cargo.toml
Comparison of binary sizes
| Binary | Size before | Size afterwards |
| ------ | ----------- | --------------- |
| cargo-audit | 21Mb | 13Mb |
| platforms-data-gen | 2.9Mb | 2.0Mb |
| platforms-table-gen | 485Kb | 369Kb |
| rustsec-admin | 22Mb | 14Mb |
> Enable LTO and strip symbols in release builds

- Cargo.lock
- admin/Cargo.toml
- admin/src/osv_export.rs
- cargo-audit/src/auditor.rs
- rustsec/Cargo.toml
- rustsec/src/cached_index.rs
- rustsec/src/error.rs
- rustsec/src/lib.rs
- rustsec/src/osv/advisory.rs
- rustsec/src/repository/git/modification_time.rs
Try to avoid some of the worst offenders in requiring semver-incompatible bumps.
> rustsec: privatize some dependencies
