rustsec/rustsec

Cargo.lock
Cargo.toml
src/main.rs

At least, I think this is how you do it...

Make cargo-audit a proper cargo subcommand

---

src/main.rs

Provides an Error notification and an instruction to the user to "Run \"Cargo build\" to generate lockfile before running audit".

Handle error and instruct the user to generate a lockfile before audit

---

src/display.rs
src/lockfile.rs
src/main.rs

Having everything in main.rs is a bit unwieldy

Factor main.rs apart into a few separate files

---

src/display.rs
src/lockfile.rs
src/main.rs

Refactor/cleanup error handling in the display code, and finish extracting all
display-related code into display.rs

Clean up display handling code

---

src/main.rs
src/shell.rs

Renames display.rs -> shell.rs and factors code for displaying advisories and
other messages back into main.rs

Cleanup shell handling code

---

.travis.yml
src/main.rs
src/shell.rs

Run rustfmt 0.8.2-nightly (5e599251 2018-07-02)
Fix clippy 0.0.212 nits

rustfmt + clippy fixups

---

Cargo.toml
src/main.rs

Support for printing the version

cargo audit --version

---

src/main.rs

prevent --help from exiting with error

---

.travis.yml
appveyor.yml

Runs a more extensive set of tests on Travis CI, including a self-audit by running `cargo run audit`

.travis.yml: rustsec, clippy, self-audit via cargo run (fixes #81)

---

Cargo.lock
Cargo.toml

Changelog: iqlusioninc/abscissa#98

Upgrade to abscissa v0.2.0

---

src/commands/audit.rs

Allows using an exiting clone of the RustSec advisory DB repo without eagerly fetching it.

Implement `--no-fetch` (closes #93)

---

src/commands/audit.rs

...by passing `-` as the `--file` option.

Add support for reading lockfiles from STDIN (closes #67)

---

audit.toml.example
src/commands/audit.rs
src/config.rs
src/presenter.rs

...and associated `[output.deny_warnings]` configuration option.

Add `--deny-warnings` option

---

Cargo.lock
Cargo.toml

Changelog: https://github.com/RustSec/rustsec-crate/pull/116

Update to `rustsec` crate v0.15

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
README.md

Release notes: https://github.com/iqlusioninc/abscissa/pull/142

Upgrade to Abscissa v0.4; MSRV 1.36

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
src/application.rs
src/config.rs
src/error.rs
src/prelude.rs
src/presenter.rs
tests/acceptance.rs

Release notes:
https://github.com/iqlusioninc/abscissa/pull/178

Upgrade to Abscissa v0.5

---

Cargo.lock
src/presenter.rs

Displays a warning for each yanked crate which is currently in Cargo.lock

Warn for yanked crates (closes #170)

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
README.md
audit.toml.example

Changelog: https://github.com/RustSec/rustsec-crate/pull/141

Update `rustsec` crate to v0.17 release; MSRV 1.39+

---

Cargo.lock
Cargo.toml
src/presenter.rs

Changelog: https://github.com/RustSec/rustsec-crate/pull/144

Update `rustsec` crate requirement from 0.17 to 0.17.1

---

Cargo.lock
Cargo.toml
src/auditor.rs
src/commands/audit.rs
src/config.rs
src/presenter.rs

See release notes here:
- v0.19.0: https://github.com/RustSec/rustsec-crate/pull/169
- v0.20.0: https://github.com/RustSec/rustsec-crate/pull/171

Update `rustsec` crate to v0.20

---

src/auditor.rs

Many offline use cases when they request --no-fetch are for offline
systems that may have their advisory db from an external source such
as an internal packaged version. In these cases when we are flagged
as no fetch, we should open the database with "open" instead of
"load from repo" to support operating without git metadata.
This also sets that when in no-fetch crates.io should not be updated
for the yanked list.
Fixes https://github.com/RustSec/cargo-audit/issues/313

When running in no-fetch mode, allow accessing a non-git repo.

---

src/config.rs

Proposal how to improve the interaction between informational_warnings and deny:
https://github.com/RustSec/cargo-audit/issues/318#issuecomment-787118553
This is my proposal how specifying values for deny could influence informational_warnings accordingly. The mappings for Unmaintained and Unsound are clear and Yanked does not have a mapping.
How Warnings should be mapped is debateable.
---
Feel free to modify or close this PR. I just wanted to open this PR as a discussion basis.

Enable informational warnings with deny

---

README.md
cargo-audit/README.md
cargo-lock/README.md
cvss/README.md
platforms/README.md
rustsec/README.md

Provides some basic information about the repo structure.

README.md: add new toplevel one for workspace

---

.github/workflows/admin.yml
.github/workflows/cargo-audit.yml
.github/workflows/cargo-lock.yml
.github/workflows/cvss.yml
.github/workflows/platforms.yml
.github/workflows/rustsec.yml
.github/workflows/workspace.yml
admin/src/web/mod.rs
cargo-audit/src/application.rs
cargo-audit/src/commands/audit/fix.rs
cargo-lock/src/lockfile/encoding.rs
cargo-lock/src/package/source.rs
rustsec/tests/integration.rs

Imports the original workflows used by each of the repos which were merged into the monorepo, renaming them to match the crate name.

Workspace CI configuration

---

.github/workflows/cvss.yml
cvss/src/lib.rs

- Fix CI job name
- Fix dangling link in rustdoc

cvss: fixups

---

cargo-lock/src/lockfile/encoding.rs
cargo-lock/src/lockfile/version.rs

Note: breaking change, as this adds a new variant to `ResolveVersion` which was not previously marked as `non_exhaustive`. This change makes it `non_exhaustive` so adding new versions in the future can (potentially) be done as a non-breaking change.
It doesn't appear there's anything specific that's needed for this crate to handle the V3 format, other than adding support for the explicit version field. The change in upstream cargo affects how the `Cargo.lock` is resolved from `Cargo.toml`.
Closes #351

cargo-lock: add support for V3 format

---

Cargo.lock
cargo-lock/Cargo.toml
cargo-lock/src/error.rs
rustsec/Cargo.toml
rustsec/src/error.rs

Bump to semver 1.0.0

---

cargo-audit/README.md

Add more install examples to fix layout

---

rustsec/src/repository/git/modification_time.rs

Addresses review comment by @Byron in #366
This is a no-op for the current advisory database because the repo was initialized with a README.md file, but it might prove useful in the future if we ever flatten the db repo.

Properly handle the initial commit in git modification time lookup

---

admin/src/assigner.rs
admin/src/web.rs
cargo-audit/src/auditor.rs
platforms/src/platform/req.rs
rustsec/src/advisory.rs
rustsec/src/advisory/id.rs
rustsec/src/advisory/linter.rs
rustsec/src/database.rs
rustsec/src/database/query.rs
rustsec/src/osv/ranges_for_advisory.rs
rustsec/tests/integration.rs

Removed `Query` "package_scope" field since it is unused and TODO
comment related to the field.

Fix clippy warnings

---

platforms/src/platform/platforms.rs

Getting the re-generation out of the way before I work on #529 to avoid polluting the diff for that work

regenerate `platforms` crate

---

.github/workflows/admin.yml
.github/workflows/cargo-audit.yml
.github/workflows/cargo-lock.yml
.github/workflows/cvss.yml
.github/workflows/platforms.yml
.github/workflows/release.yml
.github/workflows/rustsec.yml
cargo-audit/src/config.rs

Tests that rustdoc builds successfully

CI: add `doc` job to all crates

---

cargo-lock/src/lockfile/encoding.rs

When resolving dependencies of a V2 lockfile, uses the full name, version, and source ID from the original package.
This resolves #289 where the source ID of a dependency was not being properly extracted for V2 lockfiles.

cargo-lock: fix dependency source extraction for V2 lockfiles

---

Cargo.lock

bump openssl-src version

---

Cargo.lock
admin/Cargo.toml

Update comrak to 0.14

---

rustsec/Cargo.toml

Relax git2 requirement

---

cargo-audit/src/commands/audit/binary_scanning.rs

Make binary paths required for `cargo audit bin`

---

admin/src/web/static/css/index.css
admin/src/web/templates/index.html

Display items vertically on mobile. Should fix #752.

Fix homepage style on mobile

---

rustsec/CHANGELOG.md
rustsec/src/cached_index.rs

Handle invalid semver in registry

---

rustsec/src/osv/advisory.rs

Fixes #781.
OSV 1.2.0 added a top-level [severity field](https://ossf.github.io/osv-schema/#severity-field), allowing to specify a CVSS as severity. RustSec only exported the CVSS under [affected[].database_specific](https://ossf.github.io/osv-schema/#affecteddatabase_specific-field). With this PR, RustSec also populates the top-level severity field in the OSV advisories.
Example exported OSV json when severity is present, generated with `rustsec-admin osv crates`:
```json
{
"id": "RUSTSEC-2022-0037",
<....>
"severity": [
{
"type": "CVSS_V3",
"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
}
],
<...>
}
```
Example exported OSV json when severity is missing:
```json
{
"id": "RUSTSEC-2022-0062",
<...>
"severity": [],
<...>
}
```

Add top-level severity field to exported OSV advisories

---

.github/workflows/admin.yml
Cargo.lock
admin/Cargo.toml
admin/src/web.rs
admin/src/web/static/js/search.js

Closes #784
Also improve URI encoding handling.
I found out the website build was broken since a rust-embed update. Switched back to the working versions and adding a test to ensure the website builds.

Escape search term to prevent reflected XSS

---

cargo-audit/Cargo.toml
rustsec/Cargo.toml

Avoids creating implicit feature flags from optional deps.

Use new feature/dependency syntax

---

.github/workflows/cargo-audit.yml

The issue is not reproducible on a local Mac so re-enabling to check if it was transient

Re-enable MacOS CI with `--all-features`

---

rustsec/src/repository/git/commit.rs

Fix type inference error

---

Cargo.lock
rustsec/CHANGELOG.md
rustsec/Cargo.toml

Release `rustsec` 0.26.5

---

cargo-audit/src/commands/audit.rs
cargo-audit/tests/acceptance.rs

An updated version of #632 by @deg4uss3r
It was easier to reconstruct it from scratch than to resolve conflicts.

Fix version reporting

---

.github/workflows/cargo-audit.yml

The only non-default feature is `fix`

Do not run all tests from the default feature set twice

---

cargo-audit/README.md

Since action-rs is not maintained, I'd point to your updated version of the action.

Link to rustsec/audit-check

---

Cargo.lock
admin/Cargo.toml
cargo-audit/CHANGELOG.md
cargo-audit/Cargo.toml
rustsec/CHANGELOG.md
rustsec/Cargo.toml

New release to support sparse index

---

.github/workflows/cargo-audit.yml
.github/workflows/rustsec.yml
cargo-audit/Cargo.toml
cargo-audit/README.md
cargo-audit/src/commands/audit.rs
rustsec/Cargo.toml
rustsec/README.md

cargo-audit+rustsec: MSRV 1.65

---

.github/workflows/cargo-lock.yml
cargo-lock/Cargo.toml
cargo-lock/README.md

cargo-lock: MSRV 1.65

---

admin/src/web.rs
admin/src/web/static/js/search.js

Case-insensitive search on website

---

quitters/src/lib.rs
rustsec/src/osv/advisory.rs
rustsec/src/repository/git/commit.rs
rustsec/src/repository/git/modification_time.rs

First fixup pass on the libgit2 -> gix transition

---

.github/workflows/admin.yml
.github/workflows/rustsec.yml

With everything else being cached, these jobs are now the stragglers. Cache them too.

Even more caching for even faster CI

---

cargo-audit/src/auditor.rs
rustsec/src/cached_index.rs
rustsec/src/error.rs
rustsec/src/repository/git/repository.rs
rustsec/tests/integration.rs

Supersedes #934 
Matching PR for `tame-index`: https://github.com/EmbarkStudios/tame-index/pull/14 We will also need to plumb that change through the API once it's merged.

Less surprising locking, redux

---

Cargo.lock
admin/Cargo.toml
cargo-audit/CHANGELOG.md
cargo-audit/Cargo.toml
rustsec/CHANGELOG.md
rustsec/Cargo.toml

Release cargo-audit v0.18 and rustsec v0.28

---

Cargo.lock
cargo-audit/Cargo.toml

I forgot to bump version in #1018

Bump version to 0.18.2

---

Cargo.lock
platforms/Cargo.toml
platforms/README.md
platforms/src/platform/platforms.rs

Minor version bump on account of removal of asm.js and Solaris 10 targets

Regenerate platforms crate

---

Cargo.lock
admin/Cargo.toml
admin/src/osv_export.rs
rustsec/Cargo.toml
rustsec/src/repository/git/commit.rs
rustsec/src/repository/git/modification_time.rs

Upgrade to gix 0.58

---

cargo-lock/src/bin/cargo-lock/main.rs

fix cargo clippy warning and error

fix cargo clippy warning and error

---

.github/workflows/quitters.yml
Cargo.lock
Cargo.toml
admin/Cargo.toml
cargo-audit/Cargo.toml
cargo-lock/Cargo.toml
cvss/Cargo.toml
platforms/Cargo.toml
quitters/Cargo.toml
rustsec/Cargo.toml

Address <https://github.com/rustsec/rustsec/pull/1205#issuecomment-2189545101>

chore: leverage workspace inheritance

---

rustsec/src/error.rs
rustsec/tests/integration.rs

Fixes a few usages of nonexistent features

rustsec: Rust 1.80 fixes

---

cargo-lock/README.md

Just saw this when skimming the docs of the release candidate

V4 is supported now

---

Cargo.lock
cargo-audit/Cargo.toml

First prerelease with V4 lockfile support

cargo-audit v0.21.0-rc.0

---

Cargo.lock
admin/README.md
cargo-audit/README.md
cvss/README.md
platforms/README.header.md
platforms/README.md
rustsec/README.md

README.md(s): fix crate badges

---

Cargo.lock
Cargo.toml

Bump tame-index to 0.18 to gain support for Rust 1.85

---

.github/workflows/cargo-audit.yml
.github/workflows/cargo-lock.yml
.github/workflows/cvss.yml
.github/workflows/quitters.yml
.github/workflows/rustsec.yml
.github/workflows/workspace.yml
Cargo.lock
Cargo.toml
admin/Cargo.toml
admin/src/assigner.rs
admin/tests/acceptance.rs
cargo-audit/Cargo.toml
cargo-audit/src/commands/audit.rs
cargo-lock/Cargo.toml
cargo-lock/src/package/source.rs
cvss/Cargo.toml
rustsec/Cargo.toml
rustsec/README.md
rustsec/src/advisory/id.rs
rustsec/src/database.rs
rustsec/src/repository/git/commit.rs
rustsec/src/repository/git/repository.rs

Update dependencies, bump version, minor refactoring

---

admin/src/commands/osv.rs
admin/src/osv_export.rs
rustsec/src/osv/advisory.rs
rustsec/src/repository/git/repository.rs

Some tweaks resulting from the investigation of https://github.com/rustsec/advisory-db/issues/2301.

OSV tweaks

---

Cargo.lock
Cargo.toml
rustsec/Cargo.toml

rustsec: prepare 0.30.4 release

---

cvss/src/v4/scoring.rs

remove stray dbg!()
